
name: Test Tags

permissions: {}

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+-test*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Just a test step
        run: echo it works
